version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  buildersPay:
    image: builderspay:latest
    container_name: builderspayapi
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
    - SPRING_DATA_MONGODB_HOST=mongodb
    - SPRING_DATA_MONGODB_PORT=27017
    - SPRING_DATA_MONGODB_DATABASE=builderspay
    depends_on:
      - mongodb